// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbNidayoxoNE0AXQGRHcYuKx9EEMNVnNo',
    appId: '1:976973197594:web:cb2ca5b4d02746330dbca3',
    messagingSenderId: '976973197594',
    projectId: 'kasif-888',
    authDomain: 'kasif-888.firebaseapp.com',
    storageBucket: 'kasif-888.appspot.com',
    measurementId: 'G-5VMY6XR780',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3CLQa7WeJ5K4GfZnDA056zkpEwvyT8Vc',
    appId: '1:976973197594:android:c504e91c025f7dfd0dbca3',
    messagingSenderId: '976973197594',
    projectId: 'kasif-888',
    storageBucket: 'kasif-888.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJbEegS28N3A04PRN6qdunkvMtbdCRXi4',
    appId: '1:976973197594:ios:72e8c1ffeb1777cc0dbca3',
    messagingSenderId: '976973197594',
    projectId: 'kasif-888',
    storageBucket: 'kasif-888.appspot.com',
    iosClientId: '976973197594-goode02fvad96j4bnua08pa9cm08p3ct.apps.googleusercontent.com',
    iosBundleId: 'com.example.kasif',
  );
}
